import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main 
          className="bg-gradient-to-t from-cyan-500 to-cyan-700 
            h-screen w-full flex items-center justify-center text-white"
        >
          {children}
        </main>
      </body>
    </html>
  );
}
